name: Docs to PDF

on:
  push:
    branches:
      - main
  #   paths:
  #     - 'docs/**.md'
  #     - 'docs/images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: baileyjm02/markdown-to-pdf@v1
      #   with:
      #     input_dir: docs
      #     output_dir: pdfs
      #     images_dir: docs/images
      #     image_import: ./images
      #     build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: markdown
          path: docs

  release:
    name: Download Artifact and Create Release
    runs-on: ubuntu-latest
    needs: converttopdf

    steps:
      # Step 1: Download the "markdown" artifact from a previous workflow run
      - name: Download markdown artifact
        uses: actions/download-artifact@v3
        with:
          name: markdown  # The name of the artifact to download
          path: ./markdown.zip  # Local path to save the downloaded artifact

      # Step 2: Generate a random tag (using the current timestamp)
      - name: Generate random tag
        id: random_tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "TAG=$TAG" >> $GITHUB_ENV

      # Step 3: Create a GitHub Release with the random tag
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}  # Use the random tag generated above
          release_name: "Release ${{ env.TAG }}"
          body: "Automated release with a random tag."
          draft: false
          prerelease: false
      - name: Display structure of downloaded files
        run: ls
      - name: Upload markdown to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: markdown.zip
          asset_name: release
          asset_content_type: application/zip